### ISSUE TITLE
[plugin:vite-plugin-vue-i18n] Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by liqueflies** [intlify/nuxt3#26]
Hello, using latest version of nuxt and @intlify/nuxt3, having this nuxt config

```
  intlify: {
    localeDir: 'locales', // set the `locales` directory at source directory of your Nuxt application
    vueI18n: {
      legacy: false,
      locale: 'en',
      fallbackLocale: 'en',
      globalInjection: true,
    },
  },
```

Info:
```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.0`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `target`, `head`, `css`, `loading`, `publicRuntimeConfig`, `plugins`, `components`, `buildModules`, `modules`, `intlify`, `pwa`, `sanity`, `gtm`, `sitemap`, `robots`
- Runtime Modules:  `@nuxtjs/robots@2.5.0`
- Build Modules:    `nuxt-windicss@2.0.12`, `@intlify/nuxt3@0.1.8`
------------------------------
```

and a folder `locales` with a file called it.json and en.json I got the following error:

```
[plugin:vite-plugin-vue-i18n] Cannot read property 'message' of undefined
/Users/lorenzo/secretproject/locales/it.json
    at Object.newOptions.onError (/Users/lorenzo/secretproject/node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
    at Object.newOptions.onError (/Users/lorenzo/secretproject/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
    at newOptions.onError (/Users/lorenzo/secretproject/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
    at emitError (/Users/lorenzo/secretproject/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:845:13)
    at parseLinked (/Users/lorenzo/secretproject/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:979:17)
    at parseMessage (/Users/lorenzo/secretproject/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1036:36)
    at parseResource (/Users/lorenzo/secretproject/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1075:25)
    at Object.parse (/Users/lorenzo/secretproject/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1090:21)
    at Object.baseCompile (/Users/lorenzo/secretproject/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1402:24)
    at Object.generateMessageFunction (/Users/lorenzo/secretproject/node_modules/@in
```

Of course I am not seeing translated content if I dismiss the error.

Thanks for help,
L.

**Comment by lukaszflorczak** [comment]
I have the same problem? Any progress or solution?

**Comment by alxtr1bal** [comment]
Same here, any solution to this ?

**Comment by alxtr1bal** [comment]
solved by replacing @ in locales with {'@'}
