### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Thy3634** [intlify/nuxt3#45]
## Reproduce
just build

## environment
@intlify/nuxt3@0.1.10
nuxt3@latest: 3.0.0-27356801.e9128f3

## terminal log out:
$ nuxi build
Nuxt CLI v3.0.0-27356801.e9128f3                                                                                                                                                     17:10:57

 WARN  Error when using sourcemap for reporting an error: Can't resolve original location of error.                                                                                  17:11:03  

 ERROR  'handleFlatJson' is not exported by node_modules\@intlify\nuxt3\node_modules\@intlify\core-base\dist\core-base.esm-bundler.js, imported by node_modules\vue-i18n\dist\vue-i18n.runtime.esm-bundler.js
file: E:/nut/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:7:29
5:   */
6: import { getGlobalThis, format, makeSymbol, isPlainObject, isArray, hasOwn, isObject, isBoolean, isString, isRegExp, isFunction, assign, isNumber, warn, createEmitter, isEmptyObject } from '@intlify/shared';
7: import { createCompileError, handleFlatJson, createCoreContext, updateFallbackLocale, resolveValue, clearDateTimeFormat, clearNumberFormat, setAdditionalMeta, NOT_REOSLVED, isTranslateFallbackWarn, isTranslateMissingWarn, parseTranslateArgs, translate, MISSING_RESOLVE_VALUE, parseDateTimeArgs, datetime, parseNumberArgs, number, getLocaleChain, setDevToolsHook } from '@intlify/core-base';
                                ^
8: import { ref, getCurrentInstance, computed, watch, createVNode, Text, h, Fragment, inject, onMounted, onUnmounted, isRef } from 'vue';
9: import { setupDevtoolsPlugin } from '@vue/devtools-api';

 ERROR  'handleFlatJson' is not exported by node_modules\@intlify\nuxt3\node_modules\@intlify\core-base\dist\core-base.esm-bundler.js, imported by node_modules\vue-i18n\dist\vue-i18n.runtime.esm-bundler.js

  at error (node_modules\rollup\dist\shared\rollup.js:158:30)
  at Module.error (node_modules\rollup\dist\shared\rollup.js:12423:16)
  at Module.traceVariable (node_modules\rollup\dist\shared\rollup.js:12808:29)
  at ModuleScope.findVariable (node_modules\rollup\dist\shared\rollup.js:11588:39)
  at FunctionScope.findVariable (node_modules\rollup\dist\shared\rollup.js:6953:38)
  at ChildScope.findVariable (node_modules\rollup\dist\shared\rollup.js:6953:38)
  at TrackingScope.findVariable (node_modules\rollup\dist\shared\rollup.js:6953:38)
  at BlockScope.findVariable (node_modules\rollup\dist\shared\rollup.js:6953:38)
  at BlockScope.findVariable (node_modules\rollup\dist\shared\rollup.js:6953:38)
  at BlockScope.findVariable (node_modules\rollup\dist\shared\rollup.js:6953:38)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vis97c** [comment]
Having the same issue on a fresh install.

**Comment by chawakorn40** [comment]
remove vue-i18n it's work for me.
