### ISSUE TITLE
Cannot start nuxt: `Cannot find module './module.json'`

### ISSUE THREAD

**Issue by adriaanvanrossum** [intlify/nuxt3#56]
```
Nuxt CLI v3.0.0-rc.1-27515112.2d202b5

  > Local:    http://localhost:3005/ 
  > Network:  http://10.1.1.205:3005/
  > Network:  http://10.1.0.251:3005/

 ERROR  Cannot start nuxt:  Cannot find module './module.json' 
Require stack:
- /Users/adriaan/Developer/simpleanalytics/marketing-site/node_modules/@intlify/nuxt3/dist/module.cjs

  Require stack:
  - node_modules/@intlify/nuxt3/dist/module.cjs
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
  at Function.resolve (internal/modules/cjs/helpers.js:98:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:192841)
  at jiti (node_modules/jiti/dist/jiti.js:1:195025)
  at node_modules/@intlify/nuxt3/dist/module.cjs:4:37
  at jiti (node_modules/jiti/dist/jiti.js:1:196506)
  at requireModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:255:26)
  at normalizeModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:408:53)
  at installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:391:47)
  at initNuxt (node_modules/nuxt/dist/index.mjs:1364:13)
```

```js
{
  "devDependencies": {
    "@headlessui/vue": "^1.6.0",
    "@heroicons/vue": "^1.0.6",
    "@intlify/nuxt3": "^0.2.0",
    "@nuxtjs/tailwindcss": "^5.0.3",
    "imageoptim-cli": "^3.0.7",
    "nuxt": "npm:nuxt3@latest" // v3.0.0-rc.1-27515112.2d202b5
  }
}
```

**Comment by adriaanvanrossum** [comment]
Seems to be duplicate of https://github.com/intlify/nuxt3/issues/55
