### ISSUE TITLE
After adding `"@intlify/nuxt3"` to `buildModules` in `nuxt.config.ts` there's a Nuxt error

### ISSUE THREAD

**Issue by PiotrekPKP** [intlify/nuxt3#63]
I installed `"@intlify/nuxt3"` and added it to my `buildModules`.

After adding `"@intlify/nuxt3"` to `buildModules` in `nuxt.config.ts` there's a Nuxt error:
```
__vite_ssr_import_2__.default is not a function
```

The error occurs even after reinstallation of package and after removing `.nuxt` directory.

Stacktrace:
```
at ./.nuxt/dist/server/server.mjs:3590:60
at fn (./.nuxt/dist/server/server.mjs:396:27)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:41:19)
at callWithNuxt (./.nuxt/dist/server/server.mjs:398:23)
at applyPlugin (./.nuxt/dist/server/server.mjs:353:29)
at Module.applyPlugins (./.nuxt/dist/server/server.mjs:363:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:46:7)
at async renderToString (./node_modules/vue-bundle-renderer/dist/index.mjs:252:19)
at async ./.nuxt/dev/index.mjs:486:20
```

The line that shows an error is this one:
```
const loadedOptions = await __vite_ssr_import_2__.default();
```

This line is in a code block:
```
const { vueApp: app } = nuxt;
  const loadedOptions = await __vite_ssr_import_2__.default();
  if (!isEmpty(__vite_ssr_import_3__.default)) {
    loadedOptions.messages = __vite_ssr_import_3__.default;
  }
  const i18n = __vite_ssr_import_0__.createI18n({
    legacy: false,
    globalInjection: true,
    locale: "en",
    ...loadedOptions
  });
  app.use(i18n);
```

**Comment by dnlnrs** [comment]
Hey @PiotrekPKP! Are you using Nuxt3 rc2?
I'm having the same issue and I'm trying to understand how to solve this

Thanks!

**Comment by adriaanvanrossum** [comment]
Seems like it's related to https://github.com/intlify/nuxt3/issues/64

**Comment by PiotrekPKP** [comment]
> Seems like it's related to #64

More like #64 is related to this issue ;)

**Comment by FlyingWraptor** [comment]
> > Seems like it's related to #64
> 
> More like #64 is related to this issue ;)

Except that one got traction, sadly enough. I think it's best to just close this issue as the problem is easily reproduceable

**Comment by FlyingWraptor** [comment]
As this issue is the last one that's open.

Overriding the following packages in package.json will temporarily fix it by forcing rc-1 to be used
```json
"overrides": {
    "nuxi": "3.0.0-rc.1",
    "nuxt": "3.0.0-rc.1",
    "@nuxt/kit": "3.0.0-rc.1",
    "@nuxt/schema": "3.0.0-rc.1",
    "@nuxt/vite-builder": "3.0.0-rc.1"
  }
  ```

**Comment by FlyingWraptor** [comment]
I've created a PR #65 as per @exreplay's findings: https://github.com/intlify/nuxt3/issues/64#issuecomment-1127416063

The patch has been found to work with RC.3

**Comment by FlyingWraptor** [comment]
Merged for v0.2.2

**Comment by phcent** [comment]
> Merged for v0.2.2

invalid

**Comment by Rasul1996** [comment]
@kazupon

**Comment by androcado** [comment]
Same issue. Do you have an idea? THX

npm install --save-dev @intlify/nuxt3

nuxt.config.ts
export default defineNuxtConfig({
    ssr: false, // Client-side only rendering (false)
    buildModules: ['@intlify/nuxt3']
})

error: 
Uncaught SyntaxError: The requested module '/_nuxt/.nuxt/intlify.vuei18n.options.mjs' does not provide an export named 'default'

---
"devDependencies": {
    "@intlify/nuxt3": "^0.2.2",
    "bulma": "^0.9.4",
    "nuxt": "3.0.0-rc.4",
    "sass": "^1.51.0"
  },

**Comment by FlyingWraptor** [comment]
@androcado Try adding @intlify/nuxt3 to modules, not buildModules.

**Comment by androcado** [comment]
> @androcado Try adding @intlify/nuxt3 to modules, not buildModules in the nuxt config.

Thanks. But same issue:

export default defineNuxtConfig({
modules: ['@intlify/nuxt3'],
})

error: 
__vite_ssr_import_2__.default is not a function

**Comment by FlyingWraptor** [comment]
Odd, because I can't reproduce it

**Comment by FlyingWraptor** [comment]
@androcado What does your package-lock.json look like?

I've recreated the application using your exact specification, albeit on MacOS
<img width="393" alt="image" src="https://user-images.githubusercontent.com/38633741/174236187-87ccbdef-70fd-44d0-9bff-0fc7d2eca674.png">

Would you mind sharing your package-lock please?
I'll try to get a windows device to test the same config out

**Comment by androcado** [comment]
Here is the package lock file. thx for the support

![test1](https://user-images.githubusercontent.com/14692286/174482632-6c398f76-4b6d-4748-bb7f-82c428960b52.jpg)

![Unbenanq343nt-2](https://user-images.githubusercontent.com/14692286/174482909-25292252-7e09-4236-9678-c87609dba551.jpg)

[package-lock.zip](https://github.com/intlify/nuxt3/files/8935623/package-lock.zip)

**Comment by kkurt** [comment]
I am getting the same error, is there any fix/solutuion ?

**Comment by exreplay** [comment]
@kkurt @androcado do you guys have the same problem with a fresh project just using the `@intlify/nuxt3` package?

I'm having multiple projects running on `nuxt@3.0.0-rc.4` with `@intlify/nuxt3@0.2.2` and not having any issues.

**Comment by FlyingWraptor** [comment]
> @kkurt @androcado do you guys have the same problem with a fresh project just using the `@intlify/nuxt3` package?
> 
> I'm having multiple projects running on `nuxt@3.0.0-rc.4` with `@intlify/nuxt3@0.2.2` and not having any issues.

is this on Mac or linux by chance?

**Comment by FlyingWraptor** [comment]
@kkurt What version of node and NPM are you running? My tests also failed when running on Windows.

MacOS and Linux work fine

**Comment by kkurt** [comment]
> @kkurt What version of node and NPM are you running? My tests also failed when running on Windows.
> 
> MacOS and Linux work fine (for me)

NodeJS : 16.15.1
Npm: 8.13.1

**Comment by androcado** [comment]
Thanks, with the last update it works for me.

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/178130428-859690be-ed9c-492b-b87e-3b12c5ff2097.png)

**Comment by SVV-team** [comment]
https://github.com/intlify/nuxt3/issues/72#issuecomment-1184394295

For nuxt3 i18 from community
