### ISSUE TITLE
This module is causing problems with Pinia installation

### ISSUE THREAD

**Issue by mikesiiro** [intlify/nuxt3#71]
When I install the module I get this error: `[nuxt] [request error] [🍍]: getActivePinia was called with no active... `

Without the module, Nuxt & Pinia works perfect.

## Tested on:
- windows 10 and windows 11
- nuxt 3.0.0-rc.3 and 3.0.0-rc.4

## Console output:

```bash
[Vue warn]: injection "Symbol(pinia)" not found.
[Vue warn]: Unhandled error during 
execution of setup function        
  at <AppHeader>
[nuxt] [request error] [🍍]: getActivePinia was called with no active 
Pinia. Did you forget to install pinia?
        const pinia = createPinia()        app.use(pinia)
This will fail in production.      
  at Module.useStore (/C:/www/test-m580/node_modules/pinia/dist/pinia.mjs:1638:19)
  at setup (/C:/www/test-m580/.nuxt/dist/server/server.mjs:21773:45)  
  at _sfc_main.setup (/C:/www/test-m580/.nuxt/dist/server/server.mjs:21832:23)
  at callWithErrorHandling (C:\www\test-m580\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
  at setupStatefulComponent (C:\www\test-m580\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7084:29)
  at setupComponent (C:\www\test-m580\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7039:11)   
  at renderComponentVNode (C:\www\test-m580\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:172:17)
  at Module.ssrRenderComponent (C:\www\test-m580\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:608:12)
  at _sfc_ssrRender (/C:/www/test-m580/.nuxt/dist/server/server.mjs:21714:31)
  at renderComponentSubTree (C:\www\test-m580\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:253:13)
[nuxt] [request error] __vite_ssr_import_2__.default is not a function  at /C:/www/test-m580/.nuxt/dist/server/server.mjs:6069:60
  at fn (/C:/www/test-m580/.nuxt/dist/server/server.mjs:433:27)       
  at Object.callAsync (/C:/www/test-m580/node_modules/unctx/dist/index.mjs:41:19)
  at callWithNuxt (/C:/www/test-m580/.nuxt/dist/server/server.mjs:435:23)
  at applyPlugin (/C:/www/test-m580/.nuxt/dist/server/server.mjs:390:29)
  at Module.applyPlugins (/C:/www/test-m580/.nuxt/dist/server/server.mjs:400:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async createNuxtAppServer (/C:/www/test-m580/.nuxt/dist/server/server.mjs:46:7)
  at async Object.renderToString (/C:/www/test-m580/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
  at async /C:/www/test-m580/.nuxt/dev/index.mjs:1096:20
[nuxt] [request error] __vite_ssr_import_2__.default is not a function  at /C:/www/test-m580/.nuxt/dist/server/server.mjs:6069:60
  at fn (/C:/www/test-m580/.nuxt/dist/server/server.mjs:433:27)       
  at Object.callAsync (/C:/www/test-m580/node_modules/unctx/dist/index.mjs:41:19)
  at callWithNuxt (/C:/www/test-m580/.nuxt/dist/server/server.mjs:435:23)
  at applyPlugin (/C:/www/test-m580/.nuxt/dist/server/server.mjs:390:29)
  at Module.applyPlugins (/C:/www/test-m580/.nuxt/dist/server/server.mjs:400:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async createNuxtAppServer (/C:/www/test-m580/.nuxt/dist/server/server.mjs:46:7)
  at async Object.renderToString (/C:/www/test-m580/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
  at async /C:/www/test-m580/.nuxt/dev/index.mjs:1096:20

```

**Comment by FlyingWraptor** [comment]
What does your nuxt config look like?
Make sure you use modules instead of buildModules.

Are you using [@pinia/nuxt](https://www.npmjs.com/package/@pinia/nuxt)?

My config works completely fine:
```js
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  modules: [
    '@pinia/nuxt',
    '@intlify/nuxt3'
  ],
  intlify: {
    localeDir: 'locales',
    vueI18n: {
      locale: 'en'
    },
  }
})
```

**Comment by sesa668674** [comment]
> What does your nuxt config look like? Make sure you use modules instead of buildModules.
> 
> Are you using [@pinia/nuxt](https://www.npmjs.com/package/@pinia/nuxt)?
> 
> My config works completely fine:
> 
> ```js
> import { defineNuxtConfig } from 'nuxt'
> 
> // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
> export default defineNuxtConfig({
>   modules: [
>     '@pinia/nuxt',
>     '@intlify/nuxt3'
>   ],
>   intlify: {
>     localeDir: 'locales',
>     vueI18n: {
>       locale: 'en'
>     },
>   }
> })
> ```


Thanks, I was using `buildModules` but now I changed it to `modules` but it still not working.

This is my updated nuxt config:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
	css: ['@/assets/styles/main.scss'],

	modules: ['@pinia/nuxt', '@vueuse/nuxt', '@intlify/nuxt3', 'nuxt-lodash'],

	// module config for 'nuxt-lodash'
	lodash: {
		prefix: 'use',
		prefixSkip: ['is'],
		exclude: ['map'],
		alias: [
			['camelCase', 'stringToCamelCase'], // => useStringToCamelCase
			['kebabCase', 'stringToKebabCase'] // => useStringToKebabCase
		]
	},

	// module config for '@vueuse/nuxt'
	vueuse: {
		ssrHandlers: true
	},

	// module config for '@intlify/nuxt3'
	intlify: {
		localeDir: 'locales',
		vueI18n: {
			locale: 'en'
		}
	}
})

```

This is the error I get on the webpage:

```
500
__vite_ssr_import_2__.default is not a function

at /C:/www/test-m580/.nuxt/dist/server/server.mjs:6070:60
at fn (/C:/www/test-m580/.nuxt/dist/server/server.mjs:434:27)
at Object.callAsync (/C:/www/test-m580/node_modules/unctx/dist/index.mjs:41:19)
at callWithNuxt (/C:/www/test-m580/.nuxt/dist/server/server.mjs:436:23)
at applyPlugin (/C:/www/test-m580/.nuxt/dist/server/server.mjs:391:29)
at Module.applyPlugins (/C:/www/test-m580/.nuxt/dist/server/server.mjs:401:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async createNuxtAppServer (/C:/www/test-m580/.nuxt/dist/server/server.mjs:46:7)
at async Object.renderToString (/C:/www/test-m580/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
at async /C:/www/test-m580/.nuxt/dev/index.mjs:1096:20
```

Like I said, if I remove `@intlify/nuxt3` module, all works fine!

**Comment by FlyingWraptor** [comment]
This looks like it is a windows only issue related to #63

**Comment by sesa668674** [comment]
> This looks like it is a windows only issue related to #63

Thanks for your reply @FlyingWraptor 

Is there any solution to this ?

**Comment by max5432112345** [comment]
> > This looks like it is a windows only issue related to #63
> 
> Thanks for your reply @FlyingWraptor
> 
> Is there any solution to this ?

Unix
